environment: local

spring:
  application:
    name: backend
  cloud:
    gcp:
      firestore:
        emulator:
          enabled: true
          host: localhost
          port: 8080
      storage:
        emulator:
          host: localhost
          port: 9199
      auth:
        emulator:
          host: localhost
          port: 9099
logging:
  level:
    root: INFO
    com.softeng.backend: DEBUG # Change to INFO if you don't want debug logs

server:
  port: 3000
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"
