environment: production

spring:
  cloud:
    gcp:
      project-id: ${GOOGLE_CLOUD_PROJECT}
      database-id: ${GOOGLE_CLOUD_DATABASE}
      credentials:
          location: classpath:firebase-prod.json

logging:
  level:
    root: INFO
    com.softeng.backend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true