spring:
  profiles: ci
  cloud:
    gcp:
      project-id: qdog-6aca2
      firestore:
        emulator:
          enabled: true
        credentials:
          location: ""

logging:
  level:
    root: INFO
    com.softeng.backend: DEBUG # Change to INFO if you don't want debug logs

server:
  port: 3000
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"