spring:
  cloud:
    gcp:
      firestore:
        emulator:
          enabled: true
        project-id: qdog-6aca2
  application:
    name: backend
server:
  port: 3000
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"