environment: local

spring:
  application:
    name: backend
  cloud:
    gcp:
      database-id: ${GOOGLE_CLOUD_DATABASE}
      credentials:
        location: classpath:firebase-admin.json

logging:
  level:
    root: INFO
    com.softeng.backend: DEBUG # Change to INFO if you don't want debug logs

server:
  port: 3000
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"
