package com.softeng.backend.controllers.pet;

import com.softeng.backend.dto.OwnerDTO;
import com.softeng.backend.dto.PetDTO;
import com.softeng.backend. models.pet.Pet;
import com.softeng.backend.services.pet.IPetService;
import com.softeng.backend.services.user.owner.IOwnerService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;

// The following class was partially developed with boilerplate and code
// generated by ChatGPT ((https://chat.openai.com) and IntelliJ autocomplete

@Slf4j
@RestController
@RequestMapping("/api/v1/owners")
public class PetController implements IPetController {

    private final IOwnerService ownerService;

    private final IPetService petService;


    @Autowired
    public PetController(IOwnerService ownerService, IPetService petService) {
        this.ownerService = ownerService;
        this.petService = petService;
    }

    /*****************************************************************************
     * CREATE
     ******************************************************************************/
    @PostMapping("/{ownerId}/pets")
    @Override
    public ResponseEntity<PetDTO> createPet(@PathVariable String ownerId, @RequestBody Pet pet) {

        if (ownerId.isBlank() || pet == null || !pet.isValid()) {
            return ResponseEntity.badRequest().build();
        }

        try {
            PetDTO result = petService.createPet(ownerId, pet);

            if (result.getPet().getId() != null) {
                return ResponseEntity.ok().body(result);
            }

            return ResponseEntity.notFound().build();
        } catch (ExecutionException | InterruptedException e) {
            return ResponseEntity.internalServerError().build();
        }
    }

    /*****************************************************************************
     * READ
     ******************************************************************************/

    @GetMapping("/{ownerId}/pets")
    @Override
    public ResponseEntity<List<Map<String, Object>>> getPets(@PathVariable String ownerId, @RequestParam String petId) {
        List<Map<String, Object>> result;

        List<PetDTO> pets;
        try {
            if (petId.isBlank()) {
                pets = petService.getPetsByOwnerId(ownerId);
            } else {
                pets = petService.getPetById(ownerId, petId);
            }

            if (!petId.isBlank() && pets.isEmpty()) {
                return ResponseEntity.notFound().build();
            }

            // Steam map generated with IntelliJ autocomplete
            result = pets.stream().map(PetDTO::toMap).toList();

        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        return ResponseEntity.ok().body(result);
    }

    /*****************************************************************************
     * UPDATE
     ******************************************************************************/
    @PutMapping("/{ownerId}/pets")
    @Override
    public ResponseEntity<OwnerDTO> updatePet(@PathVariable String ownerId, @RequestParam String petId,
                                              @RequestBody Pet pet) {
        OwnerDTO updated;

        if (ownerId.isBlank() || pet == null || !pet.isValid()) {
            return ResponseEntity.badRequest().build();
        }

        try {
            updated = ownerService.updatePet(ownerId, pet);
            petService.updatePet(ownerId, petId, pet);
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        if (updated.getId() != null) {
            return ResponseEntity.ok().body(updated);
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * DELETE
     ******************************************************************************/
    @DeleteMapping("/{ownerId}/pets")
    @Override
    public ResponseEntity<OwnerDTO> removePet(@PathVariable String ownerId, @RequestParam String petId) {
        OwnerDTO updated;

        if (ownerId.isBlank() || petId.isBlank()) {
            return ResponseEntity.badRequest().build();
        }

        try {
            PetDTO removed = petService.deletePet(ownerId, petId);

            if (removed.getId() == null) {
                return ResponseEntity.notFound().build();
            }

            updated = ownerService.removePet(ownerId, petId);
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        if (updated.getId() != null) {
            return ResponseEntity.ok().body(updated);
        } else {
            return ResponseEntity.notFound().build();
        }
    }
}
