package com.softeng.backend.controllers.pet;

import com.softeng.backend.dto.DiaryDTO;
import com.softeng.backend.dto.OwnerDTO;
import com.softeng.backend.dto.PetDTO;
import com.softeng.backend.models.diary.Diary;
import com.softeng.backend. models.pet.Pet;
import com.softeng.backend.repository.pet.PetRepository;
import com.softeng.backend.services.pet.IPetService;
import com.softeng.backend.services.user.owner.IOwnerService;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Arrays;
import java.util.Map;
import java.util.concurrent.ExecutionException;

// The following class was partially developed with boilerplate and code
// generated by ChatGPT ((https://chat.openai.com) and IntelliJ autocomplete

@RestController
@RequestMapping("/api/v1/pets")
public class PetController implements IPetController {

    private static final Logger logger = LoggerFactory.getLogger(PetController.class);
    private final IOwnerService ownerService;
    private final IPetService petService;
    private final PetRepository petRepository;


    @Autowired
    public PetController(IOwnerService ownerService, IPetService petService, PetRepository petRepository) {
        this.ownerService = ownerService;
        this.petService = petService;
        this.petRepository = petRepository;
    }

    /*****************************************************************************
     * CREATE
     ******************************************************************************/
    @PostMapping()
    @Override
    public ResponseEntity<Map<String, Object>> createPet(@NotNull @RequestBody Pet pet) {

        if (!pet.isValid()) {
            return ResponseEntity.badRequest().build();
        }

        try {
            PetDTO result = petService.createPet(pet);

            if (result.getPet().getId() != null) {
                return ResponseEntity.ok().body(result.toMap());
            }

            return ResponseEntity.notFound().build();
        } catch (ExecutionException | InterruptedException e) {
            return ResponseEntity.internalServerError().build();
        }
    }

    /*****************************************************************************
     * READ
     ******************************************************************************/
    @GetMapping("/{petId}")
    @Override
    public ResponseEntity<Map<String, Object>> getPet(@NotNull @NotBlank @PathVariable String petId) {

        try {
            PetDTO result = petService.getPetById(petId);

            if (result.getPet().getId() != null) {
                return ResponseEntity.ok().body(result.toMap());
            }

            return ResponseEntity.notFound().build();
        } catch (ExecutionException | InterruptedException e) {
            return ResponseEntity.internalServerError().build();
        }
    }

    /*****************************************************************************
     * UPDATE
     ******************************************************************************/
    @PutMapping("/{petId}")
    @Override
    public ResponseEntity<Map<String, Object>> updatePet(@NotNull @NotBlank @PathVariable String petId, @NotNull @RequestBody Pet pet) {
        PetDTO updated;
        //TODO implement partial update
        if (!pet.isValid()) {
            return ResponseEntity.badRequest().build();
        }

        try {
            pet.setId(petId);
            ownerService.updatePet(pet.getOwnerId(), pet);
            updated = petService.updatePet(petId, pet);
        } catch (ExecutionException | InterruptedException e) {
            logger.error("ERROR LOG: Update pet endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        if (updated.getId() != null) {
            return ResponseEntity.ok().body(updated.toMap());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * DELETE
     ******************************************************************************/
    @DeleteMapping("/{petId}")
    @Override
    public ResponseEntity<Map<String, Object>> removePet(@NotNull @NotBlank @PathVariable String petId) {
        OwnerDTO updated;
        try {
            PetDTO removed = petService.deletePet(petId);
            if (!removed.getPet().isValid()) {
                return ResponseEntity.notFound().build();
            }

            String ownerId = removed.getPet().getOwnerId();
            updated = ownerService.removePet(ownerId, petId);
        } catch (ExecutionException | InterruptedException e) {
            logger.error("ERROR LOG: Update delete endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        if (updated.getId() != null) {
            return ResponseEntity.ok().body(updated.toMap());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * CREATE PET DIARY ENTRY
     ******************************************************************************/
    @PostMapping("/{petId}/diaries")
    @Override
    public ResponseEntity<Map<String, Object>> addDiaryEntry(@NotNull @NotBlank @PathVariable String petId, @NotNull @RequestBody Diary diary) {
        DiaryDTO createdDiary;
        try {
            createdDiary = petRepository.addDiaryEntry(petId, diary);
        } catch (ExecutionException | InterruptedException e) {
            logger.error("ERROR LOG: Add diary entry fail: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        }

        if (!createdDiary.getId().isBlank()) {
            return ResponseEntity.ok().body(createdDiary.toMap());
        }
        else {
            return ResponseEntity.notFound().build();
        }
    }
}
