package com.softeng.backend.controllers.pet;

import com.softeng.backend.dto.DiaryDTO;
import com.softeng.backend.dto.PetDTO;
import com.softeng.backend.exception.repository.DocumentNotFoundException;
import com.softeng.backend.models.diary.Diary;
import com.softeng.backend. models.pet.Pet;
import com.softeng.backend.services.pet.PetService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.ExecutionException;

// The following class was partially developed with boilerplate and code
// generated by ChatGPT ((https://chat.openai.com) and IntelliJ autocomplete

@Slf4j
@RestController
@RequestMapping("/api/v1/pets")
public class PetController {

    private final PetService petService;


    @Autowired
    public PetController(PetService petService) {
        this.petService = petService;
    }

    /*****************************************************************************
     * CREATE
     ******************************************************************************/
    @PostMapping()
    public ResponseEntity<Map<String, Object>> createPet(@NotNull @Valid @RequestBody Pet pet) {

        try {
            PetDTO result = petService.createPet(pet);
            return ResponseEntity.ok().body(result.toMap());
        } catch (ExecutionException | InterruptedException e) {
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * READ
     ******************************************************************************/
    @GetMapping("/{petId}")
    public ResponseEntity<Map<String, Object>> getPet(@NotNull @NotBlank @PathVariable String petId) {

        try {
            PetDTO result = petService.getPetById(petId);
            return ResponseEntity.ok().body(result.toMap());
        } catch (ExecutionException | InterruptedException e) {
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * UPDATE
     ******************************************************************************/
    @PutMapping("/{petId}")
    public ResponseEntity<Map<String, Object>> updatePet(@NotNull @NotBlank @PathVariable String petId, @NotNull @Valid @RequestBody Pet pet) {
        PetDTO updated;

        try {
            updated = petService.updatePet(petId, pet);
            return ResponseEntity.ok().body(updated.toMap());
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Update pet endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * DELETE
     ******************************************************************************/
    @DeleteMapping("/{petId}")
    public ResponseEntity<Map<String, Object>> removePet(@NotNull @NotBlank @PathVariable String petId) {
        try {
            petService.deletePet(petId);
            return ResponseEntity.noContent().build();
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Update delete endpoint failed: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }
    }

    /*****************************************************************************
     * CREATE PET DIARY ENTRY
     ******************************************************************************/
    @PostMapping("/{petId}/diaries")
    public ResponseEntity<Map<String, Object>> addDiaryEntry(@NotNull @NotBlank @PathVariable String petId, @NotNull @Valid @RequestBody Diary diary) {
        DiaryDTO createdDiary;
        try {
            createdDiary = petService.addDiaryEntry(petId, diary);
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Add diary entry fail: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }

        return ResponseEntity.ok().body(createdDiary.toMap());
    }

    @GetMapping("/{petId}/diaries")
    public ResponseEntity<List<Map<String, Object>>> getDiaryEntryInRange(@NotNull @NotBlank @PathVariable String petId,
                                                                          @RequestParam(defaultValue = "1970-01-01T00:00:00Z") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Date from,
                                                                          @RequestParam(defaultValue = "9999-12-31T00:00:00Z") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Date to,
                                                                          @RequestParam(defaultValue = "1000") @NotNull int limit) {
        if (!from.before(to)) {
            return ResponseEntity.badRequest().build();
        }

        List<DiaryDTO> diaryDTOs;
        try {
            diaryDTOs = petService.getDiaryEntryInRange(petId, from, to, limit);
        } catch (ExecutionException | InterruptedException e) {
            log.error("ERROR LOG: Get diary entry fail: {}", Arrays.toString(e.getStackTrace()));
            return ResponseEntity.internalServerError().build();
        } catch (DocumentNotFoundException e) {
            return ResponseEntity.notFound().build();
        }

        List<Map<String, Object>> response = diaryDTOs.stream().map(DiaryDTO::toMap).toList();

        return ResponseEntity.ok().body(response);
    }
}
