package com.softeng.backend.services.socket;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

//generated by Copilot when asked to register vet online sessions
@Service
public class OnlineVetService {
    private final ConcurrentHashMap<String, String> sessionIdToVetIds = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, String> vetIdToSessionId = new ConcurrentHashMap<>();

    public void addVetIds(@NotNull @NotBlank String sessionId, @NotNull @NotBlank String vetId) {
        sessionIdToVetIds.put(sessionId, vetId);
        vetIdToSessionId.put(vetId, sessionId);
    }

    public void removeSession(@NotNull @NotBlank String sessionId) {
        String vetId = sessionIdToVetIds.remove(sessionId);
        if (vetId != null) {
            vetIdToSessionId.remove(vetId);
        }
    }

    public boolean isOnline(@NotNull @NotBlank String vetId) {
        return vetIdToSessionId.containsKey(vetId);
    }

    public List<String> getOnlineVetIds() {
        return vetIdToSessionId.keySet().stream().sorted().collect(Collectors.toList());
    }
}
