package com.softeng.backend.config.socket;

import java.security.Principal;

//The following code is generated by Copilot when asked to send message to a user over STOMP WebSocket
public class StompPrincipal implements Principal {
    private final String userId;

    public StompPrincipal(String userId) {
        this.userId = userId;
    }

    @Override
    public String getName() {
        return userId;
    }
}
