package com.softeng.backend.listener;

import com.softeng.backend.models.enums.RequestStatus;
import com.softeng.backend.models.socket.RequestMessage;
import com.softeng.backend.services.socket.OnlineVetService;
import com.softeng.backend.services.socket.RequestVetService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.messaging.SessionConnectEvent;
import org.springframework.web.socket.messaging.SessionDisconnectEvent;

import java.util.List;

//generated by Copilot when asked to remove offline vets on disconnect
@Slf4j
@Component
public class WebSocketEventListener implements IWebSocketEventListener {

    private final OnlineVetService onlineVetService;
    private final RequestVetService requestVetService;
    private final SimpMessagingTemplate template;

    @Autowired
    public WebSocketEventListener(OnlineVetService onlineVetService,RequestVetService requestVetService, SimpMessagingTemplate template) {
        this.onlineVetService = onlineVetService;
        this.requestVetService = requestVetService;
        this.template = template;
    }

    @Override
    @EventListener
    public void handleSessionDisconnect(SessionDisconnectEvent event) {
        String sessionId = event.getSessionId();
        String userId = event.getUser() != null ? event.getUser().getName() : null;
        if (userId != null) {
            List<String> userIds = requestVetService.removeAllRequestsByUserId(userId);
            for (String counterpartId : userIds) {
                // notify counterparts that the user has disconnected
                RequestMessage disconnectMessage = new RequestMessage(userId, counterpartId, "empty", RequestStatus.CANCELED);
                template.convertAndSendToUser(counterpartId, "/queue/requests", disconnectMessage);
            }
        }
        //TODO: only send update if removal happened
        onlineVetService.removeSession(sessionId);
        template.convertAndSend("/topic/online", onlineVetService.getOnlineVetIds());
        log.info("Session Disconnected for user: {}", userId);
    }

    @Override
    @EventListener
    public void handleSessionConnect(SessionConnectEvent event) {
        //log
        String userId = event.getUser() != null ? event.getUser().getName() : null;
        log.info("Received a session connect event from {}", userId);
    }
}
